### PR TITLE
Move  to file scope so that it is preserved through the runtime of th…

### LINKED ISSUE #84: Installation fails to proceed after selecting AUR helper
**Describe the bug**
While testing stuff out on my desktop I ran ./install-on-arch.sh and made it to the aur helper prompt. Upon responding no (because I already have paru installed), the installation failed with the error

```bash
./install-on-arch.sh: line 101: -S: command not found
```

**To Reproduce**
1. Run ./install-on-arch.sh
2. Select your AUR helper
3. Respond no to installing the helper

**Expected behavior**
Installation should proceed to the end

**Screenshots**
Screenshot_2021-07-22-11_3840x1080

**Desktop (please complete the following information):**
 - OS:
[neofetch.txt](https://github.com/Axarva/dotfiles-2.0/files/6865950/neofetch.txt)

### PR DESCRIPTION
**Pull request by Shahab96**
- Move  to file scope so that it is preserved through the runtime of the script, for arch.

Currently $HELPER only exists within the case statement, so once the selection is made the actual variable is not stored beyond the esac and thus we get the " -S is not a command" error.

Closes #84

### CODE REVIEW

File: install-on-arch.sh [hunk 1]
```diff
@@ -70,6 +70,8 @@ clear
 echo "We need an AUR helper. It is essential. 1) paru       2) yay"
 read -r -p "What is the AUR helper of your choice? (Default is paru): " num
 
+HELPER="paru"
```
Comment (Shahab96) [inline install-on-arch.sh:73]: Since paru is the default we can just set it here, if the user doesn't select anything the value will already be set, so we're good. This will also allow the value to be scoped to the file rather than the case block

**Review by Axarva — COMMENTED** [review]
Maybe setting the line on the top of the file would be a better choice?

File: install-on-arch.sh [hunk 2]
```diff
@@ -90,7 +89,8 @@ then
 	(cd ~/.srcs/$HELPER/ && makepkg -si )
```
Comment (Axarva) [inline install-on-arch.sh:89]: I think the package installation part is missing here. Maybe the line `$HELPER -S picom-jonaburg-git acpi candy-icons-git wmctrl alacritty playerctl dunst xmonad-contrib jq xclip maim rofi-greenclip` should be outside the `if` statement?

File: install-on-arch.sh [hunk 3]
```diff
@@ -90,7 +89,8 @@ then
...
 else
     echo "Looks like you've already got $HELPER installed, let's proceed then."
-	$HELPER -S picom-jonaburg-git acpi candy-icons-git wmctrl alacritty playerctl dunst xmonad-contrib jq xclip maim rofi-greenclip
+    $HELPER -S picom-jonaburg-git acpi candy-icons-git wmctrl alacritty playerctl dunst xmonad-contrib jq xclip maim rofi-greenclip
+    exit 1;
```
Comment (Axarva) [inline install-on-arch.sh:93]: This `exit 1` is no longer necessary, is it?

**Review by Axarva — CHANGES_REQUESTED** [review]
I've left a few comments

**Comment by Axarva** [comment]
And a final thing:
image

Just figured we could utterly reduce our case statement to this or even just an if statement.

File: install-on-arch.sh (hunk 2 above)
Comment (Shahab96) [reply install-on-arch.sh:89]: Yeah I don't see a reason to keep it in the if statement if we are installing the helper automatically. I'll move it out.

**Comment by Shahab96** [comment]
> And a final thing:
> image
> 
> Just figured we could utterly reduce our case statement to this or even just an if statement.

Agreed, an if would be enough here we no longer need a case block.

**Review by Axarva — APPROVED** [review]
